"""Publish a baked floor map as a latched nav_msgs/OccupancyGrid on /map.

This is the runtime half of tools/bake_floor_map.py: that tool slices the floor
meshes into a PNG + YAML pair under maps/, and this node serves it.

WHY NOT nav2_map_server
-----------------------
nav2's map_server does exactly this, but it is a lifecycle node -- it needs a
lifecycle manager to configure and activate it before it publishes, which is a
lot of moving parts for a fixture whose entire job is "be reliably up before the
planner asks". It also makes the whole nav2 stack a hard dependency of a package
that otherwise only ships meshes. This node is ~100 lines and has neither
problem.

The published grid is LATCHED (transient-local durability), matching map_server
and rtabmap, so a subscriber that starts late still receives it. That property
is load-bearing here: the vector field subscribes well after this node starts.
"""

import os

import numpy as np
import rclpy
from nav_msgs.msg import OccupancyGrid
from rclpy.node import Node
from rclpy.qos import (
    QoSDurabilityPolicy,
    QoSHistoryPolicy,
    QoSProfile,
    QoSReliabilityPolicy,
)


def _parse_map_yaml(path):
    """Read the map_server YAML fields this node needs.

    Hand-rolled rather than importing PyYAML: the file is generated by our own
    tool and has a fixed, flat shape, and this keeps the package's runtime
    dependencies to rclpy + numpy + pillow.
    """
    fields = {}
    with open(path) as fh:
        for line in fh:
            line = line.split("#", 1)[0].strip()
            if not line or ":" not in line:
                continue
            key, _, value = line.partition(":")
            fields[key.strip()] = value.strip()

    def num_list(text):
        return [float(v) for v in text.strip("[]").split(",")]

    return {
        "image": fields["image"],
        "resolution": float(fields["resolution"]),
        "origin": num_list(fields["origin"]),
        "negate": int(fields.get("negate", "0")),
        "occupied_thresh": float(fields.get("occupied_thresh", "0.65")),
        "free_thresh": float(fields.get("free_thresh", "0.196")),
    }


def load_occupancy_grid(yaml_path):
    """Turn a map_server-style PNG + YAML pair into (data, width, height, meta).

    Follows the standard map_server convention: pixel value is mapped to an
    occupancy probability p = (255 - px) / 255 (inverted when negate is set), then
    thresholded into the trinary {free, occupied, unknown} encoding the ROS
    OccupancyGrid uses.
    """
    from PIL import Image

    meta = _parse_map_yaml(yaml_path)
    image_path = os.path.join(os.path.dirname(yaml_path), meta["image"])
    pixels = np.array(Image.open(image_path).convert("L"))

    # ROS grids index row 0 at y_min; image row 0 is the top of the picture.
    pixels = np.flipud(pixels)

    occupancy = (255.0 - pixels.astype(np.float64)) / 255.0
    if meta["negate"]:
        occupancy = 1.0 - occupancy

    data = np.full(pixels.shape, -1, dtype=np.int8)
    data[occupancy >= meta["occupied_thresh"]] = 100
    data[occupancy <= meta["free_thresh"]] = 0

    height, width = pixels.shape
    return data.reshape(-1), width, height, meta


class MapPublisher(Node):
    def __init__(self):
        super().__init__("map_publisher")

        self.declare_parameter("yaml_filename", "")
        self.declare_parameter("frame_id", "map")
        self.declare_parameter("topic", "/map")
        self.declare_parameter("publish_period", 0.0)

        yaml_filename = self.get_parameter("yaml_filename").value
        frame_id = self.get_parameter("frame_id").value
        topic = self.get_parameter("topic").value
        period = float(self.get_parameter("publish_period").value)

        if not yaml_filename:
            raise RuntimeError("map_publisher requires the yaml_filename parameter")
        if not os.path.isfile(yaml_filename):
            raise RuntimeError(f"map not found: {yaml_filename}")

        data, width, height, meta = load_occupancy_grid(yaml_filename)

        self._msg = OccupancyGrid()
        self._msg.header.frame_id = frame_id
        self._msg.info.resolution = meta["resolution"]
        self._msg.info.width = width
        self._msg.info.height = height
        self._msg.info.origin.position.x = meta["origin"][0]
        self._msg.info.origin.position.y = meta["origin"][1]
        self._msg.info.origin.orientation.w = 1.0
        self._msg.data = data.tolist()

        # Latched, like map_server and rtabmap: subscribers that start later
        # (the vector field does) still get the map without us republishing.
        qos = QoSProfile(
            depth=1,
            history=QoSHistoryPolicy.KEEP_LAST,
            reliability=QoSReliabilityPolicy.RELIABLE,
            durability=QoSDurabilityPolicy.TRANSIENT_LOCAL,
        )
        self._pub = self.create_publisher(OccupancyGrid, topic, qos)
        self._publish()

        # Optional heartbeat, off by default. Latching covers late subscribers;
        # this is only for tools that ignore durability.
        if period > 0.0:
            self.create_timer(period, self._publish)

        free = int((data == 0).sum())
        occupied = int((data == 100).sum())
        self.get_logger().info(
            f"published {width}x{height} map @ {meta['resolution']} m/cell on {topic} "
            f"(origin {meta['origin'][0]}, {meta['origin'][1]}; "
            f"{free} free, {occupied} occupied, {data.size - free - occupied} unknown) "
            f"from {yaml_filename}"
        )

    def _publish(self):
        self._msg.header.stamp = self.get_clock().now().to_msg()
        self._pub.publish(self._msg)


def main(args=None):
    rclpy.init(args=args)
    node = None
    try:
        node = MapPublisher()
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        if node is not None:
            node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == "__main__":
    main()
